pipeline {
    agent {
        kubernetes {
          yamlFile 'Jenkins/container-builder.yaml'
        }
      }

    environment{
        SOURCE_REPOSITORY_URL = 'https://github.com/inganyoyo/hello-devops-gradle.git'
        SOURCE_REPOSITORY_BRANCH = 'main'
    }
    stages {
        // git에서 repository clone
        stage('Prepare') {
          steps {
            echo 'Clonning Repository'
            container('git'){
                git credentialsId: 'git-jenkins-token',
                    url: '${SOURCE_REPOSITORY_URL}',
                    branch: '${SOURCE_REPOSITORY_BRANCH}'
            }
          }
        }

//                 stage ('build project maven') {
//                     steps {
//                         container('maven') {
//                             dir ('./hello-springboot-mvn'){
//                                 sh """
//                                 mvn -version
//                                 mvn clean install
//                                 """
//                             }
//                         }
//                     }
//                 }

        stage ('build project gradle') {
            steps {
                container('gradle') {
                    dir ('.'){
                        sh """
                        gradle -v
                        gradle clean build -i
                        """
                    }
                }
            }
        }

        stage('Kaniko Build & Push Image') {
          steps {
            container('kaniko') {
              script {
                sh '''
                /kaniko/executor --dockerfile `pwd`/Jenkins/Dockerfile \
                                 --context `pwd` \
                                 --destination=inganyoyo/hello-devops-springboot:${BUILD_NUMBER}
                '''
              }
            }
          }
        }

        stage('K8S Manifest Update') {
          steps {
            echo 'K8S Manifest Update'
            container('maven'){
                git credentialsId: 'git-jenkins-token',
                    url: 'https://github.com/inganyoyo/hello-devops-gradle.git',
                    branch: 'main'
            }
          }
        }

    }
}

