apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-argo-deployment
  labels:
    app: hello-devops-springboot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-devops-springboot
  template:
    metadata:
      labels:
        app: hello-devops-springboot
    spec:
      containers:
        - name: hello-devops-springboot
          image: hello-devops-springboot:14
          ports:
            - containerPort: 8080
